### PR TITLE
Added WPML support

### PR DESCRIPTION
**Pull request by docryan**
This adds a select box in widget admin, with the languages from WPML, if WPML is activated.

When WPML is activated it will only show the widget content, on the web page, if the language matches the current selected language.

The widget then have to be added for each language you want to show content. But it makes it more flexible than translation the content. You can have different content for each language this way.

### CODE REVIEW

**Comment by feedmeastraycat** [comment]
Im super busy at the moment but I will have a look at this as soon as possible. I have a project coming up with WPML (my first actually). I will look into this at that time. Thanks. :)

**Comment by docryan** [comment]
Sorry to bother you. Have you had time to look at this?
I could make a test site for you with WPML so you can test it, if you like.

**Comment by feedmeastraycat** [comment]
Unfortunately not. But my summer vacation ends today and I need to start working on a side project which will use WPML. So I'll hope to get back to this soon. Sorry for the delay.

**Comment by oxyc** [comment]
imho such a features is out of scope for this plugin. There's already [Display Widgets](https://wordpress.org/plugins/display-widgets/) and [Dynamic Widgets](https://wordpress.org/plugins/dynamic-widgets/) which can limit the visibility of widgets per language.

**Comment by feedmeastraycat** [comment]
@docryan Thanks for this.

Batter late then ever ... right?

I've used your code but in a re-implementation basically. So Im gonna close this pull request now but I've added a thank you note and everything. :)

I've pushed a new master, a version 0.6.0, that I will be testing a bit more before I push it to wordpress.org and everything. But it has WPML support with a couple of other features added that I use on the project I talked about oh what is it 1,5 year ago. :)

**Pull request closed without merging**
